apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: web
    spec:
      containers:
      - name: frontend
        image: {{ .Values.images.frontend }}
        ports:
        - containerPort: {{ .Values.servicePorts.frontend }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  labels:
    app: api
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        tier: app
    spec:
      containers:
      - name: api
        image: {{ .Values.images.api }}
        ports:
        - containerPort: {{ .Values.servicePorts.api }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: {{ .Values.namespace }}
  labels:
    app: db
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        tier: data
    spec:
      containers:
      - name: db
        image: {{ .Values.images.db }}
        ports:
        - containerPort: {{ .Values.servicePorts.db }}
